"""sync models after fixes

Revision ID: 0877158a101b
Revises: ef79a424918a
Create Date: 2025-12-31 22:41:42.613666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0877158a101b'
down_revision = 'ef79a424918a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('draft', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('draft')
        batch_op.drop_column('tags')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
